// AUTO-GENERATED by tauri-specta. Do not edit by hand.
// Run `cargo test --manifest-path src-tauri/Cargo.toml export_bindings`
// (or launch the app in dev) to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfig: () => __TAURI_INVOKE<Config>("get_config"),
	saveConfig: (cfg: Config) => typedError<null, string>(__TAURI_INVOKE("save_config", { cfg })),
	scanModelsDir: () => __TAURI_INVOKE<string[]>("scan_models_dir"),
	getLaunchAtLogin: () => __TAURI_INVOKE<boolean>("get_launch_at_login"),
	setLaunchAtLogin: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_at_login", { enabled })),
	listAudioDevices: () => __TAURI_INVOKE<string[]>("list_audio_devices"),
	downloadModel: (url: string, name: string) => typedError<string, string>(__TAURI_INVOKE("download_model", { url, name })),
	/**
	 *  Best-effort delete of a model `.bin` file from the canonical models
	 *  directory. Returns `Ok(true)` if the file was actually deleted,
	 *  `Ok(false)` for safe skips (file gone, custom path outside the models
	 *  dir, or models dir doesn't exist), and `Err` only for genuine failures
	 *  (permission denied, .bin extension check failed, etc).
	 */
	deleteModelFile: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_model_file", { path })),
	loadHistory: () => __TAURI_INVOKE<HistoryEntry[]>("load_history"),
	saveHistory: (entries: HistoryEntry[]) => typedError<null, string>(__TAURI_INVOKE("save_history", { entries })),
	copyHistoryItem: (text: string) => typedError<null, string>(__TAURI_INVOKE("copy_history_item", { text })),
	/**
	 *  Cancel an in-flight recording (Recording or Transcribing state) from the
	 *  frontend. The hotkey thread calls `recorder.cancel()` directly and does not
	 *  go through this command — this command exists for future UI use (e.g. an
	 *  X button on the overlay). Registered in the invoke_handler and specta
	 *  builder so it appears in `bindings.ts` (TASK-23).
	 */
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
};

/* Types */
export type AudioConfig = {
	device: string,
};

export type CleanupConfig = {
	mode: CleanupMode,
	ollama_url: string,
	classifier_model: string,
	// Domain-specific words/phrases injected into the classifier context.
	vocabulary?: string[],
	/**
	 *  Classifier prompt template. Use `{text}` as the transcript placeholder;
	 *  it is wrapped in `<transcript>` delimiters by the cleanup module so the
	 *  user's spoken text cannot be misread as classifier instructions.
	 */
	classifier_prompt?: string,
	// Simple mode: strip common filler words (um, uh, er, hmm).
	strip_fillers?: boolean,
	// Simple mode: append a period if the transcript ends without punctuation.
	append_period?: boolean,
	// Simple mode: remove trailing Whisper artifacts like " ." and " ...".
	strip_whisper_artifacts?: boolean,
};

/**
 *  Cleanup mode. Persisted as lowercase ("off" / "regex" / "chaperone").
 * 
 *  Typed so a typo in config.toml fails to deserialize rather than silently
 *  degrading to a default behavior.
 */
export type CleanupMode = "off" | "regex" | "chaperone";

export type Config = {
	whisper?: WhisperConfig,
	cleanup?: CleanupConfig,
	audio?: AudioConfig,
	hotkey?: HotkeyConfig,
	theme?: string,
	/**
	 *  How long to keep history entries. "restart" clears on launch; "1d"/"5d"/"10d"/"30d"
	 *  removes entries older than N days. Default is "10d".
	 */
	history_auto_delete?: string,
};

export type HistoryEntry = {
	text: string,
	ts: number,
};

export type HotkeyConfig = {
	key: string,
	mode: string,
	/**
	 *  Hold Ctrl+Alt alone for ~300 ms to cancel an in-flight recording.
	 *  Default: true.
	 */
	cancel_via_ctrl_alt?: boolean,
	/**
	 *  Press Esc to cancel an in-flight recording. Off by default because
	 *  Esc is widely overloaded (modal dialogs, vim, search bars, etc.).
	 */
	cancel_via_esc?: boolean,
};

export type WhisperConfig = {
	bin: string,
	model: string,
	models?: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

