// AUTO-GENERATED by tauri-specta. Do not edit by hand.
// Run `cargo test --manifest-path src-tauri/Cargo.toml export_bindings`
// (or launch the app in dev) to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfig: () => __TAURI_INVOKE<Config>("get_config"),
	saveConfig: (cfg: Config) => typedError<null, string>(__TAURI_INVOKE("save_config", { cfg })),
	prewarmModel: () => typedError<null, string>(__TAURI_INVOKE("prewarm_model")),
	resetWarmupCache: () => typedError<null, string>(__TAURI_INVOKE("reset_warmup_cache")),
	simulateRejection: () => __TAURI_INVOKE<void>("simulate_rejection"),
	scanModelsDir: () => __TAURI_INVOKE<string[]>("scan_models_dir"),
	/**
	 *  Return the available models for a given backend family.
	 * 
	 *  - Whisper: returns the three models in the existing catalog (same IDs as
	 *    `download_model` accepts). The UI should show installed vs. not-installed
	 *    state by cross-referencing with `scan_models_dir`.
	 *  - Parakeet: returns "tdt-0.6b-v2" (English) and "tdt-0.6b-v3" (multilingual).
	 * 
	 *  `family` is a lowercase string: "whisper" | "parakeet".
	 *  Unknown values are treated as "whisper".
	 */
	listModelsForFamily: (family: string) => __TAURI_INVOKE<ModelDescriptor[]>("list_models_for_family", { family }),
	getLaunchAtLogin: () => __TAURI_INVOKE<boolean>("get_launch_at_login"),
	setLaunchAtLogin: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_at_login", { enabled })),
	resetTurbotalk: (deleteModels: boolean) => typedError<null, string>(__TAURI_INVOKE("reset_turbotalk", { deleteModels })),
	listAudioDevices: () => __TAURI_INVOKE<string[]>("list_audio_devices"),
	/**
	 *  Check whether any Logitech HID mouse (VendorID 0x046d) is currently
	 *  connected. Uses `ioreg` on macOS — fast (< 50 ms) and requires no new
	 *  FFI. On non-macOS platforms always returns false (Logitech software
	 *  interception is a macOS-only problem).
	 */
	detectLogitechMouse: () => __TAURI_INVOKE<boolean>("detect_logitech_mouse"),
	downloadModel: (modelId: string) => typedError<string, string>(__TAURI_INVOKE("download_model", { modelId })),
	cancelDownload: (modelId: string) => __TAURI_INVOKE<void>("cancel_download", { modelId }),
	/**
	 *  Download a Parakeet TDT ONNX model bundle from HuggingFace.
	 * 
	 *  Model source: https://huggingface.co/istupakov/parakeet-tdt-0.6b-v2-onnx
	 * 
	 *  Files downloaded per variant (int8 quantized — ~660 MB total):
	 *    encoder-model.int8.onnx
	 *    decoder_joint-model.int8.onnx
	 *    nemo128.onnx
	 *    vocab.txt
	 * 
	 *  Each file is downloaded separately. Progress ticks are per-file (pct within
	 *  the overall set). The download key used in progress events is
	 *  `"parakeet-<variant>"` so the frontend can show a per-variant progress bar.
	 */
	downloadParakeetModel: (variant: string) => typedError<null, string>(__TAURI_INVOKE("download_parakeet_model", { variant })),
	/**
	 *  Best-effort delete of a model `.bin` file from the canonical models
	 *  directory. Returns `Ok(true)` if the file was actually deleted,
	 *  `Ok(false)` for safe skips (file gone, custom path outside the models
	 *  dir, or models dir doesn't exist), and `Err` only for genuine failures
	 *  (permission denied, .bin extension check failed, etc).
	 */
	deleteModelFile: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_model_file", { path })),
	/**
	 *  Delete an ONNX model bundle directory for Parakeet.
	 * 
	 *  `family` is "parakeet"; `variant` is the variant slug (e.g.
	 *  "tdt-0.6b-v2"). Clears `backend_variant` when the removed bundle was the
	 *  active selection. Returns `Ok(true)` when a directory was removed,
	 *  `Ok(false)` when it was already gone.
	 */
	deleteBackendModel: (family: string, variant: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_backend_model", { family, variant })),
	loadHistory: () => __TAURI_INVOKE<HistoryEntry[]>("load_history"),
	saveHistory: (entries: HistoryEntry[]) => typedError<null, string>(__TAURI_INVOKE("save_history", { entries })),
	copyHistoryItem: (text: string) => typedError<null, string>(__TAURI_INVOKE("copy_history_item", { text })),
	/**
	 *  Cancel an in-flight dictation job from the frontend. The hotkey thread
	 *  calls `recorder.cancel()` directly and does not go through this command —
	 *  this command exists for future UI use (e.g. an X button on the overlay).
	 *  Registered in the invoke_handler and specta builder so it appears in
	 *  `bindings.ts`.
	 */
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
	startRecording: () => __TAURI_INVOKE<void>("start_recording"),
	stopRecording: () => __TAURI_INVOKE<void>("stop_recording"),
	showMainAndOpenHistory: () => __TAURI_INVOKE<void>("show_main_and_open_history"),
	// Open the TurboTalk data folder in the platform's file manager.
	openDataFolder: () => typedError<null, string>(__TAURI_INVOKE("open_data_folder")),
	/**
	 *  Open the canonical TurboTalk GitHub releases page in the user's browser.
	 *  Uses the `open` crate for non-shell URL opening on all platforms.
	 */
	openReleasesPage: () => typedError<null, string>(__TAURI_INVOKE("open_releases_page")),
	/**
	 *  Check whether `model_name` is present in the configured Ollama instance's
	 *  pulled-model list. Returns `Ok(false)` for all network / URL failures.
	 *  Only returns `Err` for panics or framework-level issues.
	 */
	checkOllamaModel: (modelName: string) => typedError<boolean, string>(__TAURI_INVOKE("check_ollama_model", { modelName })),
	/**
	 *  Scan `~/.ollama/models/blobs/` for any `*-partial*` files, which are left
	 *  behind when an `ollama pull` is interrupted mid-download. Returns `true` if
	 *  any partial blobs are found — the model manifest may exist but the model
	 *  is unusable until the blobs are complete.
	 */
	checkOllamaPartialBlobs: () => __TAURI_INVOKE<boolean>("check_ollama_partial_blobs"),
	/**
	 *  Open a validated `https://*.ollama.com` URL in the user's default browser.
	 * 
	 *  Validation:
	 *    - Must parse as a valid URL.
	 *    - Must use `https`.
	 *    - Host must be `ollama.com` or a subdomain (`*.ollama.com`).
	 * 
	 *  The allowlist is intentionally narrow — the only call site this task enables
	 *  is the "Install Ollama" button. Any other URL fails loudly.
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	/**
	 *  Ping the configured Ollama instance by hitting GET {ollama_url}/api/version.
	 *  Returns `Ok(Reachable { reachable: false, version: None })` for all expected
	 *  failure modes — only panics or Tauri framework issues produce `Err`.
	 */
	pingOllama: () => typedError<Reachable, string>(__TAURI_INVOKE("ping_ollama")),
	/**
	 *  Fire-and-forget: loads the configured classifier model into Ollama's memory
	 *  so the first real dictation doesn't cold-start. Returns immediately — the
	 *  generate runs on a background thread and its result is discarded.
	 * 
	 *  Only does anything when cleanup mode is Chaperone; safe to call at any time.
	 */
	prewarmOllama: () => __TAURI_INVOKE<void>("prewarm_ollama"),
	/**
	 *  Download a model into the user's local Ollama instance by streaming
	 *  `POST {ollama_url}/api/pull`. Emits incremental `ollama-pull-progress`
	 *  events to the frontend as each NDJSON line arrives. Returns `Ok(())` when
	 *  Ollama reports `"success"` and `Err(message)` on any unrecoverable failure.
	 * 
	 *  **No read timeout** — model pulls are multi-GB and can take several minutes
	 *  on a slow connection. The connect timeout is 5 seconds (loopback should
	 *  connect near-instantly). Cancellation is out of scope for this task.
	 */
	pullOllamaModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("pull_ollama_model", { modelName })),
	runDiagnostics: () => __TAURI_INVOKE<DiagnosticsResult>("run_diagnostics"),
	logClientEvent: (event: string, detail: string | null) => typedError<null, string>(__TAURI_INVOKE("log_client_event", { event, detail })),
	exportDiagnosticReport: (note: string | null) => typedError<ExportDiagnosticResult, string>(__TAURI_INVOKE("export_diagnostic_report", { note })),
	/**
	 *  Bundle the diagnostic report (with the tester's note) and upload it to the
	 *  configured webhook. Always writes a local copy first so nothing is lost when
	 *  the network or webhook is unavailable.
	 * 
	 *  Upload is gated behind the `dev-telegram-bugreport` Cargo feature — public
	 *  release builds never embed Telegram credentials.
	 */
	submitBugReport: (note: string) => typedError<BugReportResult, string>(__TAURI_INVOKE("submit_bug_report", { note })),
	openLogsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_logs_folder")),
	checkReadiness: () => __TAURI_INVOKE<Readiness>("check_readiness"),
	/**
	 *  Trigger the native macOS microphone prompt. Resolves to the new status
	 *  once the user dismisses the alert. If permission is already determined
	 *  (granted or denied), AVFoundation calls back synchronously with the
	 *  existing value — no second prompt is shown.
	 */
	requestMicrophonePermission: () => __TAURI_INVOKE<PermissionStatus>("request_microphone_permission"),
	/**
	 *  Trigger the native macOS Input Monitoring prompt. This adds Turbo Talk to
	 *  Privacy & Security → Input Monitoring so the user can enable keyboard-event
	 *  listening for the packaged app. If the prompt was already denied, macOS will
	 *  not show it again; the caller should deep-link to System Settings.
	 * 
	 *  Uses CGRequestListenEventAccess (CoreGraphics, macOS 12+) which is the
	 *  correct TCC path for Input Monitoring on modern macOS. Falls back to
	 *  IOHIDRequestAccess for older systems.
	 */
	requestInputMonitoringPermission: () => __TAURI_INVOKE<PermissionStatus>("request_input_monitoring_permission"),
	/**
	 *  Open a specific pane in macOS System Settings. `pane` is one of:
	 *    "accessibility" | "microphone" | "input_monitoring"
	 *  Anything else returns an error so the frontend sees a typed failure
	 *  instead of silently launching the wrong pane.
	 */
	openSystemSettings: (pane: string) => typedError<null, string>(__TAURI_INVOKE("open_system_settings", { pane })),
	/**
	 *  Restart the app. Used by the onboarding flow after the user grants
	 *  Accessibility — `AXIsProcessTrusted()` caches per-process, so a relaunch
	 *  is the only way to re-evaluate.
	 */
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	/**
	 *  Trigger the native macOS Accessibility prompt. Side-effect: auto-adds
	 *  the app to the Privacy & Security → Accessibility list (toggled off) so
	 *  the user has something to enable. Called from the onboarding flow on
	 *  step 1 before deep-linking to System Settings.
	 * 
	 *  Returns the trust status as observed at call time. AXIsProcessTrusted
	 *  caches per-process, so this will keep returning `Denied` until the user
	 *  grants and the app is restarted.
	 */
	promptForAccessibility: () => __TAURI_INVOKE<PermissionStatus>("prompt_for_accessibility"),
	/**
	 *  Debug command: set the in-memory force-onboarding flag so the frontend
	 *  shows the welcome screen immediately. Also re-enables hotkey suppression
	 *  while onboarding is active. Deletes the persistent flag so it takes
	 *  effect on the next launch too.
	 */
	resetOnboarding: () => __TAURI_INVOKE<void>("reset_onboarding"),
	/**
	 *  Called by the frontend when onboarding completes, to clear the force flag
	 *  and enable the hotkey for dictation.
	 */
	clearForceOnboarding: () => __TAURI_INVOKE<void>("clear_force_onboarding"),
	/**
	 *  Called by the frontend when all setup gates are green (or onboarding
	 *  completes). Clears both the debug force flag and the onboarding-active
	 *  state so the hotkey can arm.
	 */
	setSetupComplete: () => __TAURI_INVOKE<void>("set_setup_complete"),
	/**
	 *  Reset the TCC permission entry for Turbo Talk so the onboarding wizard
	 *  can clear stale entries left by a previous install. After this call the
	 *  bundle is no longer in the Privacy list; the caller should immediately
	 *  re-run the relevant registration path (IOHIDManager open for input
	 *  monitoring, AXIsProcessTrustedWithOptions for accessibility) so macOS
	 *  re-adds a fresh, correctly-bound entry.
	 * 
	 *  `service` must be one of: "accessibility" | "input_monitoring"
	 */
	resetTccEntry: (service: string) => typedError<null, string>(__TAURI_INVOKE("reset_tcc_entry", { service })),
};

/* Types */
export type AudioConfig = {
	device: string,
	/**
	 *  Mic warmth: how long the cpal input stream stays open after a recording
	 *  ends, in seconds. Trade-off: warm = no CoreAudio cold-start on the next
	 *  press (≈200 ms saved + pre-roll ring intact); cold = macOS restores
	 *  normal system audio routing immediately (YouTube/music stops sounding
	 *  like a phone call). 0 = OFF (close immediately on stop).
	 */
	idle_timeout_secs?: number,
};

/**
 *  Which transcription backend family to use.
 * 
 *  Persisted as lowercase ("whisper" / "parakeet").
 *  Legacy "moonshine" configs are accepted on load and normalized to Parakeet.
 */
export type BackendFamily = "whisper" | "parakeet";

export type BugReportResult = {
	// Short, human-quotable id the tester can reference (e.g. "A1B3C5").
	report_id: string,
	// Whether the report was uploaded (vs. only saved locally).
	uploaded: boolean,
	// Absolute path to the local report copy.
	report_path: string,
};

export type CleanupConfig = {
	mode: CleanupMode,
	ollama_url: string,
	classifier_model: string,
	// Domain-specific words/phrases injected into the classifier context.
	vocabulary?: string[],
	/**
	 *  Classifier prompt template. Use `{text}` as the transcript placeholder;
	 *  it is wrapped in `<transcript>` delimiters by the cleanup module so the
	 *  user's spoken text cannot be misread as classifier instructions.
	 */
	classifier_prompt?: string,
	// Simple mode: strip common filler words (um, uh, er, hmm).
	strip_fillers?: boolean,
	/**
	 *  Anti-vocabulary: word-to-word replacement or word removal applied after
	 *  all other cleanup. Each entry is either a bare word (removed entirely)
	 *  or a "from→to" pair (replaced). Intended for persistent spelling errors
	 *  from the transcriber (e.g. "groq→grok").
	 */
	antivocabulary?: string[],
	// Simple mode: append a period if the transcript ends without punctuation.
	append_period?: boolean,
	// Simple mode: remove trailing Whisper artifacts like " ." and " ...".
	strip_whisper_artifacts?: boolean,
};

/**
 *  Cleanup mode. Persisted as lowercase ("off" / "regex" / "chaperone").
 * 
 *  Typed so a typo in config.toml fails to deserialize rather than silently
 *  degrading to a default behavior.
 */
export type CleanupMode = "off" | "regex" | "chaperone";

export type Config = {
	whisper?: WhisperConfig,
	cleanup?: CleanupConfig,
	audio?: AudioConfig,
	hotkey?: HotkeyConfig,
	theme?: string,
	/**
	 *  How long to keep history entries. "restart" clears on launch; "1d"/"5d"/"10d"/"30d"
	 *  removes entries older than N days. Default is "10d".
	 */
	history_auto_delete?: string,
	/**
	 *  Whether to persist history entries to disk. Default: true (preserve existing behavior).
	 *  When false, no new history entries are written — existing history on disk is untouched.
	 */
	save_history?: boolean,
	/**
	 *  Whether to show the floating recording overlay pill during recording.
	 *  When false, the overlay window is hidden — the tray icon still reflects state.
	 */
	show_overlay?: boolean,
	/**
	 *  Visual density for the floating overlay: "small", "medium" (default),
	 *  or "large". Existing configs with `show_overlay = true` behave as medium.
	 */
	overlay_size?: string,
	/**
	 *  Where on the screen the overlay pill anchors: "bottom" (default) or "top".
	 *  Anything else is treated as "bottom" by the positioning code.
	 */
	overlay_position?: string,
	/**
	 *  Whether to show a small red dot near the cursor during recording.
	 *  The dot follows the mouse pointer and appears bottom-right of the hotspot.
	 *  Defaults off.
	 */
	cursor_dot_indicator?: boolean,
	// Play a sound cue when recording starts.
	sound_on_start?: boolean,
	// Play a sound cue when transcription finishes and text is pasted.
	sound_on_finish?: boolean,
	/**
	 *  Play a soft chime when a recording is cancelled (Escape, tap-mash, or
	 *  tray click). Defaults off to match the rest of the audio cues.
	 */
	sound_on_cancel?: boolean,
	// Play an error beep when dictation is filtered or pasted with issues.
	sound_on_error?: boolean,
	// Volume for sound cues, 0.0–1.0.
	sound_volume?: number,
	// Which transcription backend family to use. Default: Parakeet.
	backend?: BackendFamily,
	/**
	 *  Active variant within the chosen backend family — e.g. "tdt-0.6b-v2"
	 *  for Parakeet. Empty means use the family default in
	 *  `resolve_backend_variant`.
	 */
	backend_variant?: string,
	/**
	 *  Pause media playback (music, podcasts) when dictation starts, then
	 *  resume when the transcript is pasted. Defaults on.
	 */
	pause_media_on_dictate?: boolean,
};

/**
 *  All fields are `String` or `bool` for trivial JSON serialisation. String
 *  fields use sentinel values ("ok", "missing", "error: …") so the frontend
 *  can render them without additional type magic.
 */
export type DiagnosticsResult = {
	// `std::env::consts::OS` — "macos", "linux", "windows", …
	platform: string,
	/**
	 *  Whether `cpal::default_host().input_devices()` returned at least one
	 *  device.
	 */
	audio_input_available: boolean,
	/**
	 *  Whether the model file configured in `Settings.whisper.model` exists
	 *  on disk.
	 */
	model_file_exists: boolean,
	// Absolute path to the model file as stored in Settings (not resolved).
	model_file_path: string,
	/**
	 *  Whether the whisper-cli sidecar binary exists at the resolved path and
	 *  is executable (unix execute-bit check on macOS).
	 */
	sidecar_available: boolean,
	/**
	 *  Absolute path to the sidecar binary that was checked, or an error
	 *  description if it could not be resolved.
	 */
	sidecar_path: string,
	// Cleanup mode from Settings: "off", "regex", or "chaperone".
	cleanup_mode: string,
	/**
	 *  Only populated when `cleanup_mode == "chaperone"`. "reachable" if
	 *  Ollama responded to an HTTP GET within 2 s; "unreachable: <reason>"
	 *  otherwise. Empty string when not checked.
	 */
	ollama_status: string,
	// "supported" on macOS; "unsupported" on other platforms.
	paste_capability: string,
	/**
	 *  OS version string (e.g. "macOS 15.4", "Windows 11 23H2", "Linux 6.8.0").
	 *  Collected via platform-specific commands at diagnostic time.
	 */
	os_version: string,
	/**
	 *  Keyboard layout identifier. Windows: locale name from GetKeyboardLayout.
	 *  macOS/Linux: empty string (not collected).
	 */
	keyboard_layout: string,
	// Default input device name as reported by cpal, or "none" / "error: …".
	default_input_device: string,
	// Number of input channels on the default device ("1", "2", "unknown").
	default_input_channels: string,
	// Preferred sample rate of the default device ("16000", "44100", "unknown").
	default_input_sample_rate: string,
	/**
	 *  Whether the whisper-server sidecar process is currently running.
	 *  "running", "not running", or "unknown (prewarm in flight)".
	 */
	whisper_server_running: string,
	/**
	 *  Paste injection method: "CGEventPost Cmd+V", "enigo Ctrl+V",
	 *  "unsupported (wayland)".
	 */
	paste_method: string,
};

export type ExportDiagnosticResult = {
	// Absolute path to the bundled report file.
	report_path: string,
	// Absolute path to the live session log (also embedded in the report).
	log_path: string,
};

export type HistoryEntry = {
	text: string,
	ts: number,
	/**
	 *  True when the transcript triggered a garbage/hallucination detector
	 *  but was still pasted. Rendered with a yellow outline in the list.
	 */
	flaky?: boolean | null,
};

export type HotkeyConfig = {
	key: string,
	mode: string,
	/**
	 *  Cancel an in-flight recording when the user presses Escape. Read on
	 *  every keystroke from the global hotkey listener — only acts while the
	 *  recorder is busy, so Escape passes through to the focused app
	 *  otherwise.
	 */
	cancel_on_esc?: boolean,
	/**
	 *  Cancel an in-flight recording when the user holds the trigger key for
	 *  `HOLD_CANCEL_DURATION` (1000 ms) while the recorder is Recording or
	 *  Transcribing. Lets the user abort without reaching for Escape.
	 */
	cancel_on_hold?: boolean,
};

/**
 *  A model descriptor returned by `list_models_for_family`.
 *  The `id` is a stable short identifier used as a download key and
 *  in progress events. The `label`, `description`, and `size` fields
 *  are display strings for the UI. `download_url` is the canonical
 *  HuggingFace URL (empty string if not directly downloadable via the
 *  existing `download_model` command). `path_hint` is the expected
 *  on-disk path after download (empty for Whisper — those use `scan_models_dir`).
 */
export type ModelDescriptor = {
	id: string,
	// Human tier label (e.g. "Recommended", "Large") — matches Whisper Models UI.
	tier: string,
	// Technical model name shown in the monospace pill (e.g. `parakeet-en-v2`).
	label: string,
	description: string,
	size: string,
	download_url: string,
	path_hint: string,
	// True when the required ONNX bundle files are present on disk.
	installed: boolean,
	// True for the recommended starter model within this backend family.
	recommended: boolean,
};

export type PermissionStatus = "granted" | "denied" | "not_determined" | "unsupported";

/**
 *  Returned by `ping_ollama`. `reachable: false` covers all expected failure
 *  modes (URL invalid, connection refused, timeout, non-2xx) so the frontend
 *  can render a "not detected" state without bouncing through typedError.
 */
export type Reachable = {
	reachable: boolean,
	version: string | null,
};

export type Readiness = {
	accessibility: PermissionStatus,
	automatic_paste: PermissionStatus,
	input_monitoring: PermissionStatus,
	microphone: PermissionStatus,
	model_present: boolean,
	// Host OS id (`macos`, `windows`, `linux`, …) for platform-aware onboarding UI.
	platform: string,
	/**
	 *  True iff all dictation gates pass — frontend uses this as the
	 *  "show onboarding vs. show main UI" switch.
	 */
	ready: boolean,
	/**
	 *  Debug override: true when `reset_onboarding` was called this session.
	 *  Frontend shows onboarding regardless of `ready` while this is set.
	 */
	force_onboarding: boolean,
};

export type WhisperConfig = {
	bin: string,
	model: string,
	models?: string[],
	/**
	 *  Enable Silero VAD pre-filter in whisper-server. When true, the server
	 *  skips silent regions before the decoder runs, preventing hallucination
	 *  on silence and speeding up transcription of recordings with long pauses.
	 *  Toggle off if a quiet speaking voice triggers false negatives.
	 */
	vad_enabled?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

