// AUTO-GENERATED by tauri-specta. Do not edit by hand.
// Run `cargo test --manifest-path src-tauri/Cargo.toml export_bindings`
// (or launch the app in dev) to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfig: () => __TAURI_INVOKE<Config>("get_config"),
	saveConfig: (cfg: Config) => typedError<null, string>(__TAURI_INVOKE("save_config", { cfg })),
	scanModelsDir: () => __TAURI_INVOKE<string[]>("scan_models_dir"),
	getLaunchAtLogin: () => __TAURI_INVOKE<boolean>("get_launch_at_login"),
	setLaunchAtLogin: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_at_login", { enabled })),
	listAudioDevices: () => __TAURI_INVOKE<string[]>("list_audio_devices"),
	downloadModel: (modelId: string) => typedError<string, string>(__TAURI_INVOKE("download_model", { modelId })),
	/**
	 *  Best-effort delete of a model `.bin` file from the canonical models
	 *  directory. Returns `Ok(true)` if the file was actually deleted,
	 *  `Ok(false)` for safe skips (file gone, custom path outside the models
	 *  dir, or models dir doesn't exist), and `Err` only for genuine failures
	 *  (permission denied, .bin extension check failed, etc).
	 */
	deleteModelFile: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_model_file", { path })),
	loadHistory: () => __TAURI_INVOKE<HistoryEntry[]>("load_history"),
	saveHistory: (entries: HistoryEntry[]) => typedError<null, string>(__TAURI_INVOKE("save_history", { entries })),
	copyHistoryItem: (text: string) => typedError<null, string>(__TAURI_INVOKE("copy_history_item", { text })),
	/**
	 *  Cancel an in-flight recording (Recording or Transcribing state) from the
	 *  frontend. The hotkey thread calls `recorder.cancel()` directly and does not
	 *  go through this command — this command exists for future UI use (e.g. an
	 *  X button on the overlay). Registered in the invoke_handler and specta
	 *  builder so it appears in `bindings.ts` (TASK-23).
	 */
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
	/**
	 *  Open the TurboTalk data folder (`~/.config/librewin/turbotalk/`) in Finder.
	 *  macOS only — uses the system `open` command.
	 */
	openDataFolder: () => typedError<null, string>(__TAURI_INVOKE("open_data_folder")),
	runDiagnostics: () => __TAURI_INVOKE<DiagnosticsResult>("run_diagnostics"),
	checkReadiness: () => __TAURI_INVOKE<Readiness>("check_readiness"),
	/**
	 *  Trigger the native macOS microphone prompt. Resolves to the new status
	 *  once the user dismisses the alert. If permission is already determined
	 *  (granted or denied), AVFoundation calls back synchronously with the
	 *  existing value — no second prompt is shown.
	 */
	requestMicrophonePermission: () => __TAURI_INVOKE<PermissionStatus>("request_microphone_permission"),
	/**
	 *  Open a specific pane in macOS System Settings. `pane` is one of:
	 *    "accessibility" | "microphone" | "input_monitoring"
	 *  Anything else returns an error so the frontend sees a typed failure
	 *  instead of silently launching the wrong pane.
	 */
	openSystemSettings: (pane: string) => typedError<null, string>(__TAURI_INVOKE("open_system_settings", { pane })),
	/**
	 *  Restart the app. Used by the onboarding flow after the user grants
	 *  Accessibility — `AXIsProcessTrusted()` caches per-process, so a relaunch
	 *  is the only way to re-evaluate.
	 */
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	/**
	 *  Trigger the native macOS Accessibility prompt. Side-effect: auto-adds
	 *  the app to the Privacy & Security → Accessibility list (toggled off) so
	 *  the user has something to enable. Called from the onboarding flow on
	 *  step 1 before deep-linking to System Settings.
	 * 
	 *  Returns the trust status as observed at call time. AXIsProcessTrusted
	 *  caches per-process, so this will keep returning `Denied` until the user
	 *  grants and the app is restarted.
	 */
	promptForAccessibility: () => __TAURI_INVOKE<PermissionStatus>("prompt_for_accessibility"),
};

/* Types */
export type AudioConfig = {
	device: string,
};

export type CleanupConfig = {
	mode: CleanupMode,
	ollama_url: string,
	classifier_model: string,
	// Domain-specific words/phrases injected into the classifier context.
	vocabulary?: string[],
	/**
	 *  Classifier prompt template. Use `{text}` as the transcript placeholder;
	 *  it is wrapped in `<transcript>` delimiters by the cleanup module so the
	 *  user's spoken text cannot be misread as classifier instructions.
	 */
	classifier_prompt?: string,
	// Simple mode: strip common filler words (um, uh, er, hmm).
	strip_fillers?: boolean,
	// Simple mode: append a period if the transcript ends without punctuation.
	append_period?: boolean,
	// Simple mode: remove trailing Whisper artifacts like " ." and " ...".
	strip_whisper_artifacts?: boolean,
};

/**
 *  Cleanup mode. Persisted as lowercase ("off" / "regex" / "chaperone").
 * 
 *  Typed so a typo in config.toml fails to deserialize rather than silently
 *  degrading to a default behavior.
 */
export type CleanupMode = "off" | "regex" | "chaperone";

export type Config = {
	whisper?: WhisperConfig,
	cleanup?: CleanupConfig,
	audio?: AudioConfig,
	hotkey?: HotkeyConfig,
	theme?: string,
	/**
	 *  How long to keep history entries. "restart" clears on launch; "1d"/"5d"/"10d"/"30d"
	 *  removes entries older than N days. Default is "10d".
	 */
	history_auto_delete?: string,
	/**
	 *  Whether to persist history entries to disk. Default: true (preserve existing behavior).
	 *  When false, no new history entries are written — existing history on disk is untouched.
	 */
	save_history?: boolean,
	/**
	 *  Whether to show the floating recording overlay pill during recording.
	 *  When false, the overlay window is hidden — the tray icon still reflects state.
	 */
	show_overlay?: boolean,
};

/**
 *  All fields are `String` or `bool` for trivial JSON serialisation. String
 *  fields use sentinel values ("ok", "missing", "error: …") so the frontend
 *  can render them without additional type magic.
 */
export type DiagnosticsResult = {
	// `std::env::consts::OS` — "macos", "linux", "windows", …
	platform: string,
	/**
	 *  Whether `cpal::default_host().input_devices()` returned at least one
	 *  device.
	 */
	audio_input_available: boolean,
	/**
	 *  Whether the model file configured in `Settings.whisper.model` exists
	 *  on disk.
	 */
	model_file_exists: boolean,
	// Absolute path to the model file as stored in Settings (not resolved).
	model_file_path: string,
	/**
	 *  Whether the whisper-cli sidecar binary exists at the resolved path and
	 *  is executable (unix execute-bit check on macOS).
	 */
	sidecar_available: boolean,
	/**
	 *  Absolute path to the sidecar binary that was checked, or an error
	 *  description if it could not be resolved.
	 */
	sidecar_path: string,
	// Cleanup mode from Settings: "off", "regex", or "chaperone".
	cleanup_mode: string,
	/**
	 *  Only populated when `cleanup_mode == "chaperone"`. "reachable" if
	 *  Ollama responded to an HTTP GET within 2 s; "unreachable: <reason>"
	 *  otherwise. Empty string when not checked.
	 */
	ollama_status: string,
	// "supported" on macOS; "unsupported" on other platforms.
	paste_capability: string,
};

export type HistoryEntry = {
	text: string,
	ts: number,
};

export type HotkeyConfig = {
	key: string,
	mode: string,
};

export type PermissionStatus = "granted" | "denied" | "not_determined" | "unsupported";

export type Readiness = {
	accessibility: PermissionStatus,
	microphone: PermissionStatus,
	model_present: boolean,
	/**
	 *  True iff all three gates pass — frontend uses this as the
	 *  "show onboarding vs. show main UI" switch.
	 */
	ready: boolean,
};

export type WhisperConfig = {
	bin: string,
	model: string,
	models?: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

